### ISSUE TITLE
Comments are not deleted, when deleting a post

### ISSUE THREAD

**Issue by sinanrassam** [sinanrassam/TracksApp#14]
Comments are not deleted after a post has been deleted. Comments need to be deleted as otherwise, we have orphan comments which is not good

**Comment by bosh-code** [comment]
Do comments store the post id as a value in the db? Can we make a php script to loop all child comments that have the same post id and delete them?

**Comment by sinanrassam** [comment]
I just need to call the already created function to delete comments that belong to a post when deleting a post.

**Comment by sinanrassam** [comment]
Issue fixed, called delete post comments function from the delete post function
