### ISSUE TITLE
Recursive feed activity

### ISSUE THREAD

**Issue by sinanrassam** [sinanrassam/TracksApp#19]
When the feed activity is already open, it can be opened again from nav drawer

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in
2. Open navigation drawer
3. tap on Feed

Maybe the app shouldn't open a new activity instead it should return back to it.

 - emulator

**Comment by niteshc132** [comment]
changed so it if your on the feed  taping on 'feed' wont do anything , working on a way to close the nav bar instead

**Comment by sinanrassam** [comment]
Fixed by Nitesh with push 8a11b99a
