### ISSUE TITLE
My Posts refreshes for ever

### ISSUE THREAD

**Issue by sinanrassam** [sinanrassam/TracksApp#20]
If the user doesn't have any posts created by themselves, my post-activity will refresh forever rather than showing that no posts exist

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as the admin user
2. open navigation drawer
3. tap on my posts

**Expected behaviour**
Display a message.

**Device you tested on**
 - emulator

**Comment by bosh-code** [comment]
Fixed this issue in an earlier commit. Was caused by the merging of the 2 post tasks. No posts were loaded and as a result, the wheel spun forever.
Latest commit fixed the new toast messages.
